(function(){var h={},mt={},c={id:"6bcd52f51e9b3dce32bec4a3997715ac",dm:["csdn.net","dingyue.programmer.com.cn","gitbook.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],icon:'',ctrk:false,align:-1,nv:0,vdur:1800000,age:31536000000,rec:1,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,aet:'a,input,button',hca:'A4452CBEAD9A9F65',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var r=void 0,s=!0,t=null,w=!1;mt.cookie={};mt.cookie.set=function(b,a,f){var e;f.K&&(e=new Date,e.setTime(e.getTime()+f.K));document.cookie=b+"="+a+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(e?"; expires="+e.toGMTString():"")+(f.ac?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:t};
mt.cookie.zb=function(b,a){try{var f="Hm_ck_"+ +new Date;mt.cookie.set(f,"is-cookie-enabled",{domain:b,path:a,K:r});var e="is-cookie-enabled"===mt.cookie.get(f)?"1":"0";mt.cookie.set(f,"",{domain:b,path:a,K:-1});return e}catch(g){return"0"}};mt.lang={};mt.lang.e=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};mt.lang.Ea=function(b){return mt.lang.e(b,"Number")&&isFinite(b)};mt.lang.ka=function(){return mt.lang.e(c.aet,"String")};
mt.lang.h=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.H=function(b,a){var f=w;if(b==t||!mt.lang.e(b,"Array")||a===r)return f;if(Array.prototype.indexOf)f=-1!==b.indexOf(a);else for(var e=0;e<b.length;e++)if(b[e]===a){f=s;break}return f};
(function(){var b=mt.lang;mt.f={};mt.f.ea=function(a){return document.getElementById(a)};mt.f.gb=function(a){if(!a)return t;try{for(var b=a.split(">"),e=document.body,g=b.length-1;0<=g;g--)if(-1<b[g].indexOf("#")){var d=b[g].split("#")[1];(e=document.getElementById(d))||(e=document.getElementById(decodeURIComponent(d)));b=b.splice(g+1,b.length-(g+1));break}for(a=0;e&&a<b.length;){var n=String(b[a]).toLowerCase();if(!("html"===n||"body"===n)){var g=0,k=b[a].match(/\[(\d+)\]/i),d=[];if(k)g=k[1]-1,n=
n.split("[")[0];else if(1!==e.childNodes.length){for(var p=0,u=0,m=e.childNodes.length;u<m;u++){var l=e.childNodes[u];1===l.nodeType&&l.nodeName.toLowerCase()===n&&p++;if(1<p)return t}if(1!==p)return t}for(p=0;p<e.childNodes.length;p++)1===e.childNodes[p].nodeType&&e.childNodes[p].nodeName.toLowerCase()===n&&d.push(e.childNodes[p]);if(!d[g])return t;e=d[g]}a++}return e}catch(q){return t}};mt.f.ha=function(a,b){var e=[],g=[];if(!a)return g;for(;a.parentNode!=t;){for(var d=0,n=0,k=a.parentNode.childNodes.length,
p=0;p<k;p++){var u=a.parentNode.childNodes[p];if(u.nodeName===a.nodeName&&(d++,u===a&&(n=d),0<n&&1<d))break}if((k=""!==a.id)&&b){e.unshift("#"+encodeURIComponent(a.id));break}else k&&(k="#"+encodeURIComponent(a.id),k=0<e.length?k+">"+e.join(">"):k,g.push(k)),e.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<d?"["+n+"]":""));a=a.parentNode}g.push(e.join(">"));return g};mt.f.mb=function(a){return(a=mt.f.ha(a,s))&&a.length?String(a[0]):""};mt.f.lb=function(a){return mt.f.ha(a,w)};mt.f.Vb=
function(a,b){for(b=b.toUpperCase();(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return t};mt.f.fb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Wb=function(a){var b={top:0,left:0};if(!a)return b;var e=mt.f.fb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());return{top:b.top+(window.pageYOffset||e.scrollTop)-(e.clientTop||0),left:b.left+(window.pageXOffset||e.scrollLeft)-(e.clientLeft||0)}};mt.f.getAttribute=function(a,
b){var e=a.getAttribute&&a.getAttribute(b)||t;if(!e&&a.attributes&&a.attributes.length)for(var g=a.attributes,d=g.length,n=0;n<d;n++)g[n].nodeName===b&&(e=g[n].nodeValue);return e};mt.f.S=function(a){var b="document";a.tagName!==r&&(b=a.tagName);return b.toLowerCase()};mt.f.ob=function(a){var f="";a.textContent?f=b.trim(a.textContent):a.innerText&&(f=b.trim(a.innerText));f&&(f=f.replace(/\s+/g," ").substring(0,255));return f};mt.f.za=function(a){var b=mt.f.S(a);"input"===b&&("button"===a.type||"submit"===
a.type)?a=a.value||"":"img"===b?(b=mt.f.getAttribute,a=b(a,"alt")||b(a,"title")||b(a,"src")):a="body"===b||"html"===b?["(hm-default-content-for-",b,")"].join(""):mt.f.ob(a);return String(a).substring(0,255)};(function(){(mt.f.Ja=function(){function a(){if(!a.V){a.V=s;for(var b=0,e=g.length;b<e;b++)g[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(b,1);return}a()}var e=w,g=[],d;document.addEventListener?d=function(){document.removeEventListener("DOMContentLoaded",
d,w);a()}:document.attachEvent&&(d=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",d),a())});(function(){if(!e)if(e=s,"complete"===document.readyState)a.V=s;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",d);window.attachEvent("onload",a);var g=w;try{g=window.frameElement==t}catch(k){}document.documentElement.doScroll&&
g&&b()}})();return function(b){a.V?b():g.push(b)}}()).V=w})();return mt.f})();mt.event={};mt.event.d=function(b,a,f){b.attachEvent?b.attachEvent("on"+a,function(a){f.call(b,a)}):b.addEventListener&&b.addEventListener(a,f,w)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=w};
(function(){var b=mt.event;mt.i={};mt.i.Da=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.i.xb=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:r;mt.i.cookieEnabled=navigator.cookieEnabled;mt.i.javaEnabled=navigator.javaEnabled();mt.i.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.i.Eb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.i.colorDepth=window.screen.colorDepth||0;mt.i.T=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.i.M=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.i.orientation=0;(function(){function a(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.i.orientation=a}a();b.d(window,"orientationchange",a)})();return mt.i})();
mt.o={};mt.o.parse=function(b){return(new Function("return ("+b+")"))()};
mt.o.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=f[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return b(e);case "boolean":return String(e);
default:if(e===t)return"null";if(e instanceof Array){var g=["["],d=e.length,f,k,p;for(k=0;k<d;k++)switch(p=e[k],typeof p){case "undefined":case "function":case "unknown":break;default:f&&g.push(","),g.push(mt.o.stringify(p)),f=1}g.push("]");return g.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+a(e.getMonth()+1)+"-"+a(e.getDate())+"T"+a(e.getHours())+":"+a(e.getMinutes())+":"+a(e.getSeconds())+'"';f=["{"];k=mt.o.stringify;for(d in e)if(Object.prototype.hasOwnProperty.call(e,d))switch(p=
e[d],typeof p){case "undefined":case "unknown":case "function":break;default:g&&f.push(","),g=1,f.push(k(d)+":"+k(p))}f.push("}");return f.join("")}}}();mt.localStorage={};mt.localStorage.Y=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(b){return w}return s};
mt.localStorage.set=function(b,a,f){var e=new Date;e.setTime(e.getTime()+f||31536E6);try{window.localStorage?(a=e.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.Y()&&(mt.localStorage.l.expires=e.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(b,a),mt.localStorage.l.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),f=b.substring(0,a)-0;if(f&&f>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.Y())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(b)}catch(e){}return t};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.Y())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(b),mt.localStorage.l.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){if(window.sessionStorage)try{window.sessionStorage.setItem(b,a)}catch(f){}};
mt.sessionStorage.get=function(b){return window.sessionStorage?window.sessionStorage.getItem(b):t};mt.sessionStorage.remove=function(b){window.sessionStorage&&window.sessionStorage.removeItem(b)};mt.Ma={};mt.Ma.log=function(b,a){var f=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=f;f.onload=function(){f.onload=t;f=window[e]=t;a&&a(b)};f.src=b};mt.pa={};
mt.pa.pb=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return b};
mt.pa.Ub=function(b,a,f,e,g){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+f+'" height="'+e+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(g||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+f+'" height="'+e+'" src="'+a+'" flashvars="'+(g||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.m=function(b,a){var f=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return f?f[3]:t};mt.url.Xb=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:t};mt.url.ib=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):t};mt.url.L=function(b){return(b=mt.url.ib(b))?b.replace(/:\d+$/,""):b};mt.url.ha=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function b(){for(var a=w,b=document.getElementsByTagName("script"),e=b.length,e=100<e?100:e,g=0;g<e;g++){var d=b[g].src;if(d&&0===d.indexOf("https://hm.baidu.com/h")){a=s;break}}return a}return h.eb=b})();var A=h.eb;
h.s={Yb:"http://tongji.baidu.com/hm-web/welcome/ico",Ia:"hm.baidu.com/hm.gif",Ta:/^(tongji|hmcdn).baidu.com$/,Oa:"tongji.baidu.com",ub:"hmmd",vb:"hmpl",Ob:"utm_medium",tb:"hmkw",Qb:"utm_term",qb:"hmci",Nb:"utm_content",wb:"hmsr",Pb:"utm_source",rb:"hmcu",Mb:"utm_campaign",I:0,F:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ma:A()||"https:"===document.location.protocol?"https:":"http:",Zb:0,Sb:6E5,Ab:6E5,$b:5E3,Tb:5,ba:1024,Rb:1,J:2147483647,Na:"hca bs kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt hh".split(" "),
N:s,va:["a","input","button"],Va:{id:"data-hm-id",aa:"data-hm-class",sa:"data-hm-xpath",content:"data-hm-content",qa:"data-hm-tag",link:"data-hm-link"},ua:"data-hm-enabled",ta:"data-hm-disabled",Bb:"https://hmcdn.baidu.com/static/tongji/plugins/",Ha:["UrlChangeTracker"]};(function(){var b={B:{},d:function(a,b){this.B[a]=this.B[a]||[];this.B[a].push(b)},G:function(a,b){this.B[a]=this.B[a]||[];for(var e=this.B[a].length,g=0;g<e;g++)this.B[a][g](b)}};return h.w=b})();
(function(){function b(b,e){var g=document.createElement("script");g.charset="utf-8";a.e(e,"Function")&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=t,e()}:g.onload=function(){e()});g.src=b;var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(g,d)}var a=mt.lang;return h.load=b})();
(function(){function b(){var b="";if(h.c.b.nv){b=encodeURIComponent(document.referrer);try{window.sessionStorage?f.set("Hm_from_"+c.id,b):a.set("Hm_from_"+c.id,b,864E5)}catch(g){}}else try{b=(window.sessionStorage?f.get("Hm_from_"+c.id):a.get("Hm_from_"+c.id))||""}catch(d){}return b}var a=mt.localStorage,f=mt.sessionStorage;return h.ya=b})();
(function(){var b=mt.lang,a=mt.f,f={Q:function(b,g){return function(d){var n=d.target||d.srcElement;if(n){var k=n.getAttribute(b.X);d=d.clientX+":"+d.clientY;if(k&&k===d)n.removeAttribute(b.X);else if(g&&0<g.length&&(n=a.lb(n))&&n.length)if(k=n.length,d=n[n.length-1],1E4>k*d.split(">").length)for(d=0;d<k;d++)f.La(b,n[d]);else f.La(b,d)}}},La:function(a,g){for(var d={},f=String(g).split(">").length,k=0;k<f;k++)d[g]="",g=g.substring(0,g.lastIndexOf(">"));a&&(b.e(a,"Object")&&a.wa)&&a.wa(d)},Cb:function(a,
b){return function(d){(d.target||d.srcElement).setAttribute(a.X,d.clientX+":"+d.clientY);a&&a.r&&(b?a.r(b):a.r("#"+encodeURIComponent(this.id),d.type))}}};return h.da=f})();
(function(){var b=mt.f,a=mt.o,f=mt.event,e=mt.lang,g=h.da,d={X:"HM_ce",Pa:function(){if(c.cetrk&&c.cetrk.length){f.d(document,"click",g.Q(d,c.cetrk));for(var e=0,k=c.cetrk.length;e<k;e++){var p;try{p=a.parse(decodeURIComponent(String(c.cetrk[e])))}catch(u){p={}}var m=p.p||"";-1===m.indexOf(">")&&(0===m.indexOf("#")&&(m=m.substring(1)),(m=b.ea(m))&&f.d(m,"click",g.Cb(d,p)))}}},wa:function(b){if(c.cetrk&&c.cetrk.length)for(var e=0,g=c.cetrk.length;e<g;e++){var f;try{f=a.parse(decodeURIComponent(String(c.cetrk[e])))}catch(m){f=
{}}b.hasOwnProperty(f.p)&&d.r(f)}},r:function(a){h.c.b.et=7;var g=a&&a.k||"",g=e.h(g),f=[];if(a&&a.a&&e.e(a.a,"Object"))for(var d in a.a)if(a.a.hasOwnProperty(d)){f.push(e.h(d));var m=b.gb(a.a[d]||""),m=m?b.za(m):"";f.push(e.h(m))}a="";f.length&&(a="*"+f.join("*"));h.c.b.ep="ce!_iden*"+g+a;h.c.j()}};h.w.d("pv-b",d.Pa);return d})();
(function(){var b=mt.lang,a=mt.f,f=mt.event,e=mt.i,g=h.s,d=h.w,n=+new Date,k=[],p={Q:function(){return function(e){if(h.c&&h.c.N&&c.aet&&c.aet.length){var f=e.target||e.srcElement;if(f){var l=h.c.va,q=a.getAttribute(f,g.ua)!=t?s:w;if(a.getAttribute(f,g.ta)==t)if(q)p.Z(p.ga(f,e));else{var d=a.S(f);if(b.H(l,"*")||b.H(l,d))p.Z(p.ga(f,e));else for(;f.parentNode!=t;){var q=f.parentNode,d=a.S(q),k="a"===d&&b.H(l,"a")?s:w,d="button"===d&&b.H(l,"button")?s:w,v=a.getAttribute(q,g.ua)!=t?s:w;if(a.getAttribute(q,
g.ta)==t&&(k||d||v)){p.Z(p.ga(q,e));break}f=f.parentNode}}}}}},ga:function(f,d){var l={},q=g.Va;l.id=a.getAttribute(f,q.id)||a.getAttribute(f,"id")||"";l.aa=a.getAttribute(f,q.aa)||a.getAttribute(f,"class")||"";l.sa=a.getAttribute(f,q.sa)||a.mb(f);l.content=a.getAttribute(f,q.content)||a.za(f);l.qa=a.getAttribute(f,q.qa)||a.S(f);l.link=a.getAttribute(f,q.link)||a.getAttribute(f,"href")||"";l.type=d.type||"click";q=b.Ea(f.offsetTop)?f.offsetTop:0;"click"===d.type?q=e.Da?d.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):d.pageY:"touchend"===d.type&&(d.na&&b.e(d.na.changedTouches,"Array")&&d.na.changedTouches.length)&&(q=d.na.changedTouches[0].pageY);l.Lb=q;return l},Z:function(a){var e=b.h;a=[+new Date-(h.c.C!==r?h.c.C:n),e(a.id),e(a.aa),e(a.qa),e(a.sa),e(a.link),e(a.content),a.type,a.Lb].join("*");p.$(a);b.e(this.P(),"Function")&&this.P()()},$:function(a){a.length>g.ba||(encodeURIComponent(k.join("!")+a).length>g.ba&&(p.r(k.join("!")),k=[]),k.push(a))},r:function(a){h.c.b.et=5;h.c.b.ep=
a;h.c.j()},P:function(){return function(){k&&k.length&&(p.r(k.join("!")),k=[])}}};b.ka()&&""!==c.aet&&d.d("pv-b",function(){f.d(document,"click",p.Q());"ontouchend"in document&&f.d(window,"touchend",p.Q());f.d(window,"unload",p.P())});return p})();
(function(){var b=mt.event,a=mt.i,f=h.s,e=h.w,g=+new Date,d=[],n=t,k={ab:function(){return function(){h.c&&(h.c.N&&c.aet&&c.aet.length)&&(window.clearTimeout(n),n=window.setTimeout(function(){k.Ra(a.T()+a.M())},150))}},Ra:function(a){k.$([+new Date-(h.c.C!==r?h.c.C:g),a].join("*"))},$:function(a){if(encodeURIComponent(d.join("!")+a).length>f.ba||3<d.length)k.r(d.join("!")),d=[];d.push(a)},r:function(b){h.c.b.et=6;h.c.b.vh=a.M();h.c.b.ep=b;h.c.j()},P:function(){return function(){d&&d.length&&(k.r(d.join("!")),
d=[])}}};mt.lang.ka()&&""!==c.aet&&e.d("pv-b",function(){b.d(window,"scroll",k.ab());b.d(window,"unload",k.P())});return k})();
(function(){var b=mt.f,a=h.s,f=h.load,e=h.ya;h.w.d("pv-b",function(){var g=a.protocol+"//crs.baidu.com/";c.rec&&b.Ja(function(){for(var d=0,n=c.rp.length;d<n;d++){var k=c.rp[d][0],p=c.rp[d][1],u=b.ea("hm_t_"+k);if(p&&!(2==p&&!u||u&&""!==u.innerHTML))u="",u=Math.round(Math.random()*a.J),u=4==p?g+"hl.js?"+["siteId="+c.id,"planId="+k,"rnd="+u].join("&"):g+"t.js?"+["siteId="+c.id,"planId="+k,"from="+e(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
u].join("&"),f(u)}})})})();(function(){var b=h.s,a=h.load,f=h.ya;h.w.d("pv-b",function(){if(c.trust&&c.vcard){var e="https://tag.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+f(),"rnd="+Math.round(Math.random()*b.J),"hm=1"].join("&");a(e)}})})();
(function(){function b(){function a(b){function e(){}for(var f=s,d=0,l=0,q=t,y=t,z=b.length,v=0,x=t,d=0;d<z;d++)if(q=b[d],q.chromeVer===n){f=s;y=q.tests;v=y.length;for(l=0;l<v;l++)if(e=g[y[l].name],e()!==y[l].expect){f=w;break}if(v&&f){x={name:"360browser",type:q.type,version:q.ver};break}}return x}var b=[];b.push({ver:"8.3",type:"fast",tests:[{name:"seamlessiframe",expect:1}],chromeVer:"42"});var g={pointerevents:function(){return"maxTouchPoints"in window.navigator?1:"msMaxTouchPoints"in window.navigator||
"mozMaxTouchPoints"in window.navigator||"webkitMaxTouchPoints"in window.navigator?9:0},webgl3D:function(){for(var a="webgl ms-webgl experimental-webgl moz-webgl opera-3d webkit-3d ms-3d 3d".split(" "),b=a.length,e="",f=document.createElement("canvas"),l=w,d=0;d<b;d++)try{if(f.getContext(a[d])){l=s;e=a[d];break}}catch(g){}return l?"webgl"===e?1:9:0},seamlessiframe:function(){return"seamless"in document.createElement("iframe")?1:0},speechsynthesis:function(){return"speechSynthesis"in window?1:"webkitSpeechSynthesis"in
window||"mozSpeechSynthesis"in window||"oSpeechSynthesis"in window||"msSpeechSynthesis"in window?9:0}},d=t,n=function(){var a=navigator.userAgent.toLowerCase().match(/chrome\/(\d+)/i);return a?a[1]:"-1"}();"-1"!==n&&(d=a(b));return d}var a=function(){var a=navigator.userAgent.toLowerCase();if(0<=a.indexOf("chrome")){var a=(a=a.match(/chrome\/(\d+)/))?a[1]:-1,e=window.document,g="track"in e.createElement("track"),e="scoped"in e.createElement("style"),d="v8Locale"in window,n=document.createElement("canvas"),
k="seamless"in document.createElement("iframe"),p=w;try{n.getContext("webgl")&&(p=s)}catch(u){}if(n=b())return"fast"===n.type?7:1;if(!p&&"31"===a)return 1;if(!(k=(k||!p)&&"38"===a))if(k=g)if(k=!e)if(k=!d){var m;a:{k=window.navigator.mimeTypes;for(m in k)if("application/vnd.chromium.remoting-viewer"===k[m].type){m=s;break a}m=w}k=!m&&46>+a}if(k)return 7;if(g&&e&&d)return 1}return-1}();return h.Wa=a})();
(function(){function b(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.ca.jb()+","+h.ca.hb();h.c.j()}}function a(){clearTimeout(x);var b;z&&(b="visible"==document[z]);v&&(b=!document[v]);k="undefined"==typeof b?s:b;if((!n||!p)&&k&&u)y=s,l=+new Date;else if(n&&p&&(!k||!u))y=w,q+=+new Date-l;n=k;p=u;x=setTimeout(a,100)}function f(a){var b=document,l="";if(a in b)l=a;else for(var e=["webkit","ms","moz","o"],v=0;v<e.length;v++){var d=e[v]+a.charAt(0).toUpperCase()+a.slice(1);if(d in b){l=
d;break}}return l}function e(l){if(!("focus"==l.type||"blur"==l.type)||!(l.target&&l.target!=window))u="focus"==l.type||"focusin"==l.type?s:w,a()}var g=mt.event,d=h.w,n=s,k=s,p=s,u=s,m=+new Date,l=m,q=0,y=s,z=f("visibilityState"),v=f("hidden"),x;a();(function(){var l=z.replace(/[vV]isibilityState/,"visibilitychange");g.d(document,l,a);g.d(window,"pageshow",a);g.d(window,"pagehide",a);"object"==typeof document.onfocusin?(g.d(document,"focusin",e),g.d(document,"focusout",e)):(g.d(window,"focus",e),
g.d(window,"blur",e))})();h.ca={jb:function(){return+new Date-m},hb:function(){return y?+new Date-l+q:q}};d.d("pv-b",function(){g.d(window,"unload",b())});d.d("duration-send",b());d.d("duration-done",function(){l=m=+new Date;q=0});return h.ca})();
(function(){var b=mt.lang,a=h.s,f=h.load,e={yb:function(e){if((window._dxt===r||b.e(window._dxt,"Array"))&&"undefined"!==typeof h.c){var d=h.c.R();f([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(d)].join(""),e)}},Kb:function(a){if(b.e(a,"String")||b.e(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Za=e})();
(function(){function b(a,b,e,d){if(!(a===r||b===r||d===r)){if(""===a)return[b,e,d].join("*");a=String(a).split("!");for(var v,f=w,g=0;g<a.length;g++)if(v=a[g].split("*"),String(b)===v[0]){v[1]=e;v[2]=d;a[g]=v.join("*");f=s;break}f||a.push([b,e,d].join("*"));return a.join("!")}}function a(b){for(var d in b)if({}.hasOwnProperty.call(b,d)){var f=b[d];e.e(f,"Object")||e.e(f,"Array")?a(f):b[d]=String(f)}}var f=mt.url,e=mt.lang,g=mt.o,d=mt.i,n=h.s,k=h.w,p=h.Za,u=h.load,m={O:[],W:0,Fa:w,A:{ra:"",page:""},
init:function(){m.g=0;k.d("pv-b",function(){m.$a();m.bb()});k.d("pv-d",function(){m.cb();m.A.page=""});k.d("stag-b",function(){h.c.b.api=m.g||m.W?m.g+"_"+m.W:"";h.c.b.ct=[decodeURIComponent(h.c.getData("Hm_ct_"+c.id)||""),m.A.ra,m.A.page].join("!")});k.d("stag-d",function(){h.c.b.api=0;m.g=0;m.W=0})},$a:function(){var a=window._hmt||[];if(!a||e.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var l=arguments[b];e.e(l,"Array")&&(a.cmd[a.id].push(l),
"_setAccount"===l[0]&&(1<l.length&&/^[0-9a-f]{32}$/.test(l[1]))&&(l=l[1],a.id=l,a.cmd[l]=a.cmd[l]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},bb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],e=/^_track(Event|MobConv|Order|RTEvent)$/,d=0,v=b.length;d<v;d++){var f=b[d];e.test(f[0])?m.O.push(f):m.oa(f)}a.cmd[c.id]={push:m.oa}},cb:function(){if(0<m.O.length)for(var a=0,b=m.O.length;a<b;a++)m.oa(m.O[a]);m.O=t},oa:function(a){var b=a[0];if(m.hasOwnProperty(b)&&
e.e(m[b],"Function"))m[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(m.g|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||s===a))m.g|=2,h.c.Ba=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){m.g|=4;h.c.b.sn=h.c.Aa();h.c.b.et=0;h.c.b.ep="";h.c.b.vl=d.T()+d.M();h.c.b.kb=0;h.c.ia?(h.c.b.nv=0,h.c.b.st=4):h.c.ia=s;var b=h.c.b.u,e=h.c.b.su;h.c.b.u=n.protocol+"//"+document.location.host+a[1];m.Fa||(h.c.b.su=document.location.href);
h.c.j();h.c.b.u=b;h.c.b.su=e;h.c.C=+new Date}},_trackEvent:function(a){2<a.length&&(m.g|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=e.h(a[1])+"*"+e.h(a[2])+(a[3]?"*"+e.h(a[3]):"")+(a[4]?"*"+e.h(a[4]):""),h.c.j())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){m.W++;for(var f=(h.c.b.cv||"*").split("!"),v=f.length;v<b-1;v++)f.push("*");f[b-1]=d+"*"+e.h(a[2])+"*"+e.h(a[3]);h.c.b.cv=f.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.c.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.c.Db("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var d=e.h(a[1]);a=e.h(a[2]);if(d!==r&&a!==r){var f=decodeURIComponent(h.c.getData("Hm_ct_"+c.id)||""),f=b(f,d,1,a);h.c.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var d=e.h(a[1]);a=e.h(a[2]);if(d!==r&&a!==r){var f=m.A.ra,f=b(f,d,2,a);m.A.ra=f}}},_setPageTag:function(a){if(!(3>a.length)){var d=e.h(a[1]);a=e.h(a[2]);
if(d!==r&&a!==r){var f=m.A.page,f=b(f,d,3,a);m.A.page=f}}},_setReferrerOverride:function(a){1<a.length&&(h.c.b.su=a[1].charAt&&"/"===a[1].charAt(0)?n.protocol+"//"+window.location.host+a[1]:a[1],m.Fa=s)},_trackOrder:function(b){b=b[1];e.e(b,"Object")&&(a(b),m.g|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=g.stringify(b),h.c.j())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])m.g|=32,h.c.b.et=93,h.c.b.ep=a,h.c.j()},_trackRTPageview:function(b){b=b[1];e.e(b,"Object")&&
(a(b),b=g.stringify(b),512>=encodeURIComponent(b).length&&(m.g|=64,h.c.b.rt=b))},_trackRTEvent:function(b){b=b[1];if(e.e(b,"Object")){a(b);b=encodeURIComponent(g.stringify(b));var d=function(a){var b=h.c.b.rt;m.g|=128;h.c.b.et=90;h.c.b.rt=a;h.c.j();h.c.b.rt=b},f=b.length;if(900>=f)d.call(this,b);else for(var f=Math.ceil(f/900),k="block|"+Math.round(Math.random()*n.J).toString(16)+"|"+f+"|",v=[],x=0;x<f;x++)v.push(x),v.push(b.substring(900*x,900*x+900)),d.call(this,k+v.join("|")),v=[]}},_setUserId:function(a){a=
a[1];p.yb();p.Kb(a)},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],w===a||s===a))h.c.Ca=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],w===a||s===a))h.c.N=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.j())):k.G("duration-send");k.G("duration-done")},_require:function(a){1<a.length&&(a=a[1],n.Ta.test(f.L(a))&&u(a))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1];a=a[2];if(e.H(n.Ha,d)&&e.e(a,"Function")&&
(b.plugins=b.plugins||{},b.D=b.D||{},b.plugins[d]=a,b.z=b.z||[],a=b.z.slice(),d&&a.length&&a[0][1]===d))for(var f=0,v=a.length;f<v;f++){var x=a[f][2]||{};if(b.plugins[d]&&!b.D[d])b.D[d]=new b.plugins[d](x),b.z.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1],f=a[2]||{};if(e.H(n.Ha,d))if(b.plugins=b.plugins||{},b.D=b.D||{},b.plugins[d]&&!b.D[d])b.D[d]=new b.plugins[d](f);else{b.z=b.z||[];for(var f=0,v=b.z.length;f<v;f++)if(b.z[f][1]===d)return;b.z.push(a);m._require([t,
n.Bb+d+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=e.h(a[1]),d="";a=a[2];if(e.e(a,"Object")){var d=[],f;for(f in a)a.hasOwnProperty(f)&&(d.push(e.h(f)),d.push(e.h(a[f])));d="*"+d.join("*")}h.c.b.et=7;h.c.b.ep="ce!_iden*"+b+d;h.c.j()}}};m.init();h.Ua=m;return h.Ua})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=s,this.b={},this.Ca=this.Ba=s,this.N=l.N,this.va=g.ka()&&0<c.aet.length?c.aet.split(","):"",this.ia=w,this.init())}var a=mt.url,f=mt.Ma,e=mt.pa,g=mt.lang,d=mt.cookie,n=mt.i,k=mt.localStorage,p=mt.sessionStorage,u=mt.o,m=mt.event,l=h.s,q=h.Wa,y=h.load,z=h.w;b.prototype={la:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},
Ga:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},U:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.Ga(b,c.dm[d]))return s}else{var e=a.L(b);if(e&&this.la(e,c.dm[d]))return s}return w},R:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.la(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},fa:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.Ga(document.location.href,
d))return d.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"},nb:function(){if(!document.referrer)return l.F-l.I>c.vdur?1:4;var b=w;this.U(document.referrer)&&this.U(document.location.href)?b=s:(b=a.L(document.referrer),b=this.la(b||"",document.location.hostname));return b?l.F-l.I>c.vdur?1:4:3},getData:function(a){try{return d.get(a)||p.get(a)||k.get(a)}catch(b){}},setData:function(a,b,e){try{d.set(a,b,{domain:this.R(),path:this.fa(),K:e}),e?k.set(a,b,e):p.set(a,b)}catch(f){}},Db:function(a){try{d.set(a,
"",{domain:this.R(),path:this.fa(),K:-1}),p.remove(a),k.remove(a)}catch(b){}},Ib:function(){var a,b,e,f,g;l.I=this.getData("Hm_lpvt_"+c.id)||0;13===l.I.length&&(l.I=Math.round(l.I/1E3));b=this.nb();a=4!==b?1:0;if(e=this.getData("Hm_lvt_"+c.id)){f=e.split(",");for(g=f.length-1;0<=g;g--)13===f[g].length&&(f[g]=""+Math.round(f[g]/1E3));for(;2592E3<l.F-f[0];)f.shift();g=4>f.length?2:3;for(1===a&&f.push(l.F);4<f.length;)f.shift();e=f.join(",");f=f[f.length-1]}else e=l.F,f="",g=1;this.setData("Hm_lvt_"+
c.id,e,c.age);this.setData("Hm_lpvt_"+c.id,l.F);e=d.zb(this.R(),this.fa());if(0===c.nv&&this.U(document.location.href)&&(""===document.referrer||this.U(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=e;this.b.lt=f;this.b.lv=g},Hb:function(){for(var a=[],b=this.b.et,d=+new Date,e=0,f=l.Na.length;e<f;e++){var g=l.Na[e],k=this.b[g];"undefined"!==typeof k&&""!==k&&("tt"!==g||"tt"===g&&0===b)&&(("ct"!==g||"ct"===g&&0===b)&&("kb"!==g||"kb"===g&&3===b))&&a.push(g+"="+encodeURIComponent(k))}switch(b){case 0:this.b.rt&&
a.push("rt="+encodeURIComponent(this.b.rt));break;case 5:a.push("_lpt="+this.C);a.push("_ct="+d);break;case 6:a.push("_lpt="+this.C);a.push("_ct="+d);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},Jb:function(){this.Ib();this.b.si=c.id;this.b.sn=this.Aa();this.b.su=document.referrer;this.b.hh=window.location.hash;this.b.ds=n.Eb;this.b.cl=n.colorDepth+"-bit";this.b.ln=String(n.language).toLowerCase();this.b.ja=n.javaEnabled?1:0;this.b.ck=n.cookieEnabled?1:0;this.b.bs=q;this.b.lo=
"number"===typeof _bdhm_top?1:0;this.b.fl=e.pb();this.b.v="1.2.50";this.b.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=n.T()+n.M();var b=document.location.href;this.b.cm=a.m(b,l.ub)||"";this.b.cp=a.m(b,l.vb)||a.m(b,l.Ob)||"";this.b.cw=a.m(b,l.tb)||a.m(b,l.Qb)||"";this.b.ci=a.m(b,l.qb)||a.m(b,l.Nb)||"";this.b.cf=a.m(b,l.wb)||a.m(b,l.Pb)||"";this.b.cu=a.m(b,l.rb)||a.m(b,l.Mb)||""},init:function(){try{this.Jb(),0===this.b.nv?this.Gb():this.xa(),h.c=this,
this.Ya(),this.Xa(),z.G("pv-b"),this.Fb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(l.ma+"//"+l.Ia+"?"+b.join("&"))}},Fb:function(){function a(){z.G("pv-d")}this.Ba?(this.ia=s,this.b.et=0,this.b.ep="",this.b.vl=n.T()+n.M(),this.j(a)):a();this.C=+new Date},j:function(a){if(this.Ca){var b=this;b.b.rnd=Math.round(Math.random()*l.J);z.G("stag-b");var d=l.ma+"//"+l.Ia+
"?"+b.Hb();z.G("stag-d");b.Sa(d);f.log(d,function(d){b.Ka(d);g.e(a,"Function")&&a.call(b)})}},Ya:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.L(document.referrer)===l.Oa?1:0,f=a.m(b,"jn"),g=/^heatlink$|^select$|^pageclick$|^customevent$/.test(f);b&&(d.test(b)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*l.J),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset","utf-8"),b.setAttribute("src",l.protocol+"//"+c.js+f+".js?"+this.b.rnd),
f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(b,f))},Xa:function(){if(window.postMessage&&window.self!==window.parent){var b=this;m.d(window,"message",function(d){if(a.L(d.origin)===l.Oa){var e=d.data||{};d=e.sd||"";var e=e.jn||"",f=/^customevent$/.test(e);RegExp(c.id).test(d)&&f&&(b.b.rnd=Math.round(Math.random()*l.J),y(l.protocol+"//"+c.js+e+".js?"+b.b.rnd))}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},Sa:function(a){var b;
try{b=u.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);p.set("Hm_unsent_"+c.id,u.stringify(b))},Ka:function(a){var b;try{b=u.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?p.set("Hm_unsent_"+c.id,u.stringify(b)):this.xa()}},xa:function(){p.remove("Hm_unsent_"+
c.id)},Gb:function(){var a=this,b;try{b=u.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(e){b=[]}if(b.length)for(var d=function(b){f.log(l.ma+"//"+b,function(b){a.Ka(b)})},g=0;g<b.length;g++)d(b[g])},Aa:function(){return Math.round(+new Date/1E3)%65535}};return new b})();
(function(){var b=mt.event,a=mt.lang,f=h.s;if(c.kbtrk&&"undefined"!==typeof h.c){h.c.b.kb=a.Ea(h.c.b.kb)?h.c.b.kb:0;var e=function(){h.c.b.et=85;h.c.b.ep=h.c.b.kb;h.c.j()};b.d(document,"keyup",function(){h.c.b.kb++});b.d(window,"unload",function(){e()});setInterval(e,f.Ab)}})();var B=h.s,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.i,a=mt.lang,f=mt.event,e=mt.o;if("undefined"!==typeof h.c&&(c.med||(!b.Da||7<b.xb)&&c.cvcc)){var g,d,n,k,p=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},u=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===w)return w},m=function(b,d){var f={};f.n=g;f.t="clk";f.v=b;if(d){var l=d.getAttribute("href"),k=d.getAttribute("onclick")?""+d.getAttribute("onclick"):t,m=d.getAttribute("id")||"";n.test(l)?(f.sn="mediate",
f.snv=l):a.e(k,"String")&&n.test(k)&&(f.sn="wrap",f.snv=k);f.id=m}h.c.b.et=86;h.c.b.ep=e.stringify(f);h.c.j();for(f=+new Date;400>=+new Date-f;);};if(c.med)d="/zoosnet",g="swt",n=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,k={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(n.test(e)||n.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){d="/other-comm";g="other";n=c.cvcc.q||r;var l=c.cvcc.id||r;k={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f,g=0,k=b.length;g<k;g++)d=b[g],n!==r?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),l?(d=d.getAttribute("id"),(n.test(e)||n.test(f)||l.test(d))&&
a.push(b[g])):(n.test(e)||n.test(f))&&a.push(b[g])):l!==r&&(d=d.getAttribute("id"),l.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof k&&"undefined"!==typeof n){var q;d+=/\/$/.test(d)?"":"/";var y=function(b,e){if(q===e)return m(d+b,e),w;if(a.e(e,"Array")||a.e(e,"NodeList"))for(var f=0,g=e.length;f<g;f++)if(q===e[f])return m(d+b+"/"+(f+1),e[f]),w};f.d(document,"mousedown",function(b){b=b||window.event;q=b.target||b.srcElement;var d={};for(u(k,function(b,e){d[b]=a.e(e,"Function")?e():document.getElementById(e)});q&&
q!==document&&u(d,y)!==w;)q=q.parentNode})}}})();(function(){var b=mt.f,a=mt.lang,f=mt.event,e=mt.o;if("undefined"!==typeof h.c&&a.e(c.cvcf,"Array")&&0<c.cvcf.length){var g={Qa:function(){for(var a=c.cvcf.length,e,k=0;k<a;k++)(e=b.ea(decodeURIComponent(c.cvcf[k])))&&f.d(e,"click",g.da())},da:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=e.stringify(a);h.c.j()}}};b.Ja(function(){g.Qa()})}})();
(function(){var b=mt.event,a=mt.o;if(c.med&&"undefined"!==typeof h.c){var f=+new Date,e={n:"anti",sb:0,kb:0,clk:0},g=function(){h.c.b.et=86;h.c.b.ep=a.stringify(e);h.c.j()};b.d(document,"click",function(){e.clk++});b.d(document,"keyup",function(){e.kb=1});b.d(window,"scroll",function(){e.sb++});b.d(window,"unload",function(){e.t=+new Date-f;g()});b.d(window,"load",function(){setTimeout(g,5E3)})}})();c.spa!==r&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]));})();
