 Enabler.setProfileId(10432648);
    var devDynamicContent = {};

     devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN = [{}];
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0]._id = 0;
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Unique_ID = 1;
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Reporting_Label = "Santa Fe_MY19_Mid_Funnel_May_300x250_ROC";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Start_Date = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Start_Date.RawValue = "05/01/2019 0:00:00";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Start_Date.UtcValue = 1556668800000;
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].End_Date = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].End_Date.RawValue = "05/31/2019 23:59:00";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].End_Date.UtcValue = 1559347140000;
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_1_Headline = "{\n\"text\":\"All-New\",\"font_size\":\"17px\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_1_SubHead = "{\n\"text\":\"SANTA FE.\",\"font_size\":\"25px\",\n\"top\":\"37px\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_1_BG = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_1_BG.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_1_BG.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/73374802/dirty/300x250/bg1.jpg";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_1_Overlay = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_1_Overlay.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_1_Overlay.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/73363664/dirty/300x250/safetyPick3.png";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].IIHS_Logo = "";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].IIHS_Logo_Copy = "{\n\"text\":\"When equipped with available Forward Collision-Avoidance Assist and LED Headlights<sup style=\'vertical-align: 2px;\'>^<\/sup>.\"\n} ";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame__1_Disclaimer = "{\n\"text\":\"Ultimate Model Shown<sup>\u2666<\/sup>.\"\n}                                                                                                                                         ";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_2_Headline = "{\n\"text\":\"<small>Available HTRAC<sup style=\'vertical-align: 8px;\'>TM<\/sup><\/small><br\/>All-Wheel Drive.\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_2_BG = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_2_BG.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_2_BG.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/73363640/dirty/300x250/bg2.jpg";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_2_Overlay = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_2_Overlay.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_2_Overlay.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/64676957/dirty/blank.png";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_2_Disclaimer = "{\n\"text\":\"Ultimate model shown<sup>\u2666<\/sup>.\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_3_Headline = "{\n\"text\":\"<small>Available<\/small> <br\/>Panoramic Sunroof.\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_3_BG = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_3_BG.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_3_BG.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/73363667/dirty/300x250/bg3.jpg";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_3_Disclaimer = "{\n\"text\":\"Ultimate model shown<sup>\u2666<\/sup>.\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_4_Headline = "{\n\"text\":\"<small>Standard<\/small><br\/>Apple CarPlay \n<sup>TM<\/sup><sup>\u0394<\/sup>.\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_4_BG = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_4_BG.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_4_BG.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/73363673/dirty/300x250/bg4.jpg";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_4_Overlay = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_4_Overlay.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_4_Overlay.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/64676957/dirty/blank.png";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_4_Disclaimer = "{\n\"text\":\"\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_5_Headline = "{\n\"text\":\"World\u2019s First<br\/> \nSafe Exit Assist \n<sup>\u25CA<\/sup>.\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_5_BG = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_5_BG.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_5_BG.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/73374763/dirty/300x250/bg5.jpg";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_5_Disclaimer = "{\n\"text\":\"Available feature. <br>Ultimate model shown<sup>\u2666<\/sup>.\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_6_nameplate = "{\n\"text\":\"2019 SANTA FE\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_7_eyecatcher_copy = "{\n\"text\":\"Essential FWD starting from\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_7_eyecatcher_price = "{\n\"text\":\"<sup>$<\/sup>28,999<sup>*<\/sup>\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_6_BG = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_6_BG.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_6_BG.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/73374811/dirty/300x250/bg6.jpg";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_6_Overlay = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_6_Overlay.Type = "file";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_6_Overlay.Url = "https://s0.2mdn.net/ads/richmedia/studio/pv2/73374808/dirty/300x250/retailLogo.png";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_7_Disclaimer = "{\n\"text\":\"Ultimate model shown<sup>\u2666<\/sup>.\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Frame_7_Logo = "";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].CTA_Text = "{\n\"text\":\"Explore Santa Fe\"\n}";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Legal = "\u00AE\/\u2122 The Hyundai names, logos, product names, feature names, images and slogans are trademarks owned or licensed by Hyundai Auto Canada Corp. All other trademarks are the property of their respective owners. *Starting from price of $28,999 available on all new 2019 Santa Fe Essential FWD models. Price excludes Delivery and Destination charges of $1,905, fees, levies and all applicable charges (excluding HST; GST\/PST). Price also excludes registration, insurance, PPSA, license fees and dealer admin. fees of up to $499. Offer not available in Quebec. Fees may vary by dealer. \u2666Price of model shown: 2019 Santa Fe Ultimate Turbo AWD is $47,037.  Price includes Delivery and Destination charges of $1,905, fees, levies, and all applicable charges (excluding HST; GST\/PST). Prices exclude registration, insurance, PPSA, license fees and dealer admin. fees of up to $499. Fees may vary by dealer. *\u2666Offers available for a limited time and subject to change or cancellation without notice. Dealer may sell for less. Inventory is limited, dealer order may be required. Delivery and Destination charge includes freight, P.D.I., and a full tank of gas. Visit www.hyundaicanada.com or see dealer for complete details. \u25CAWhen the vehicle is parked, Safe Exit Assist (SEA) can alert occupants planning to exit the vehicle when a vehicle is approaching from behind. When Child Locks are active, SEA prevents the rear doors from opening if a vehicle approaching from behind is detected. SEA may not detect every vehicle and may not avoid an accident. SEA is not a substitute for attentive operation of the vehicle. Always monitor the vehicle\u2019s surroundings before any passengers exit the vehicle. See Owner\'s Manual for important details and limitations. \u2206Apple CarPlay\u2122 works with iPhone 5s, iPhone 5c, iPhone 5 and later models running the latest version of iOS 7 and above. CarPlay\u2122 may not be available on all devices and may not be available in all countries or regions. Subject to app compatibility. Visit www.apple.com for further details and any applicable limitations. Apple, Apple CarPlay, Apple Music, and iPod are trademarks of Apple Inc. ^Available feature. For more information, visit www.iihs.org.";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Legal_Button = "";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Stage_Logo = "";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Exit_URL = {};
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Exit_URL.Url = "https://www.hyundaicanada.com/en/showroom/2019/santa-fe?utm_term=santa_fe_cb_eve&%exit_suffix!#SpecialOffers";
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Default = false;
    devDynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0].Active = true;
    Enabler.setDevDynamicContent(devDynamicContent);

    var dynamic = dynamic || {};
    var fetchDynamicInfo;
    function enablerInitHandler() {
          dynamic = dynamicContent.Santa_Fe_Mid_Funnel_May_EN__Santa_Fe_MF_300x250_EN[0];

            initDynamicContent();
            initAnimation();
            document.getElementById("timeline").addEventListener('click', function(e){
              Enabler.exitOverride('Main Exit', dynamic.Exit_URL.Url);
            }, false);
    }
