(function(){var h={},mt={},c={id:"6bcd52f51e9b3dce32bec4a3997715ac",dm:["csdn.net","dingyue.programmer.com.cn","gitbook.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],icon:'',ctrk:true,align:1,nv:0,vdur:1800000,age:31536000000,rec:1,rp:[[119608, 2]],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,aet:'a,input,button',hca:'A4452CBEAD9A9F65',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var r=void 0,s=!0,t=null,w=!1;mt.cookie={};mt.cookie.set=function(b,a,f){var e;f.M&&(e=new Date,e.setTime(e.getTime()+f.M));document.cookie=b+"="+a+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(e?"; expires="+e.toGMTString():"")+(f.oc?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:t};
mt.cookie.Mb=function(b,a){try{var f="Hm_ck_"+ +new Date;mt.cookie.set(f,"is-cookie-enabled",{domain:b,path:a,M:r});var e="is-cookie-enabled"===mt.cookie.get(f)?"1":"0";mt.cookie.set(f,"",{domain:b,path:a,M:-1});return e}catch(g){return"0"}};mt.lang={};mt.lang.e=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};mt.lang.Ha=function(b){return mt.lang.e(b,"Number")&&isFinite(b)};mt.lang.na=function(){return mt.lang.e(c.aet,"String")};
mt.lang.g=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.J=function(b,a){var f=w;if(b==t||!mt.lang.e(b,"Array")||a===r)return f;if(Array.prototype.indexOf)f=-1!==b.indexOf(a);else for(var e=0;e<b.length;e++)if(b[e]===a){f=s;break}return f};
(function(){var b=mt.lang;mt.f={};mt.f.ga=function(a){return document.getElementById(a)};mt.f.tb=function(a){if(!a)return t;try{for(var b=a.split(">"),e=document.body,g=b.length-1;0<=g;g--)if(-1<b[g].indexOf("#")){var d=b[g].split("#")[1];(e=document.getElementById(d))||(e=document.getElementById(decodeURIComponent(d)));b=b.splice(g+1,b.length-(g+1));break}for(a=0;e&&a<b.length;){var n=String(b[a]).toLowerCase();if(!("html"===n||"body"===n)){var g=0,k=b[a].match(/\[(\d+)\]/i),d=[];if(k)g=k[1]-1,n=
n.split("[")[0];else if(1!==e.childNodes.length){for(var p=0,q=0,m=e.childNodes.length;q<m;q++){var l=e.childNodes[q];1===l.nodeType&&l.nodeName.toLowerCase()===n&&p++;if(1<p)return t}if(1!==p)return t}for(p=0;p<e.childNodes.length;p++)1===e.childNodes[p].nodeType&&e.childNodes[p].nodeName.toLowerCase()===n&&d.push(e.childNodes[p]);if(!d[g])return t;e=d[g]}a++}return e}catch(v){return t}};mt.f.ka=function(a,b){var e=[],g=[];if(!a)return g;for(;a.parentNode!=t;){for(var d=0,n=0,k=a.parentNode.childNodes.length,
p=0;p<k;p++){var q=a.parentNode.childNodes[p];if(q.nodeName===a.nodeName&&(d++,q===a&&(n=d),0<n&&1<d))break}if((k=""!==a.id)&&b){e.unshift("#"+encodeURIComponent(a.id));break}else k&&(k="#"+encodeURIComponent(a.id),k=0<e.length?k+">"+e.join(">"):k,g.push(k)),e.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<d?"["+n+"]":""));a=a.parentNode}g.push(e.join(">"));return g};mt.f.Ea=function(a){return(a=mt.f.ka(a,s))&&a.length?String(a[0]):""};mt.f.zb=function(a){return mt.f.ka(a,w)};mt.f.pb=
function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return t};mt.f.rb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.xb=function(a){var b={top:0,left:0};if(!a)return b;var e=mt.f.rb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());return{top:b.top+(window.pageYOffset||e.scrollTop)-(e.clientTop||0),left:b.left+(window.pageXOffset||e.scrollLeft)-(e.clientLeft||0)}};mt.f.getAttribute=function(a,b){var e=
a.getAttribute&&a.getAttribute(b)||t;if(!e&&a.attributes&&a.attributes.length)for(var g=a.attributes,d=g.length,n=0;n<d;n++)g[n].nodeName===b&&(e=g[n].nodeValue);return e};mt.f.U=function(a){var b="document";a.tagName!==r&&(b=a.tagName);return b.toLowerCase()};mt.f.Bb=function(a){var f="";a.textContent?f=b.trim(a.textContent):a.innerText&&(f=b.trim(a.innerText));f&&(f=f.replace(/\s+/g," ").substring(0,255));return f};mt.f.Ca=function(a){var b=mt.f.U(a);"input"===b&&("button"===a.type||"submit"===
a.type)?a=a.value||"":"img"===b?(b=mt.f.getAttribute,a=b(a,"alt")||b(a,"title")||b(a,"src")):a="body"===b||"html"===b?["(hm-default-content-for-",b,")"].join(""):mt.f.Bb(a);return String(a).substring(0,255)};(function(){(mt.f.La=function(){function a(){if(!a.W){a.W=s;for(var b=0,e=g.length;b<e;b++)g[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(b,1);return}a()}var e=w,g=[],d;document.addEventListener?d=function(){document.removeEventListener("DOMContentLoaded",
d,w);a()}:document.attachEvent&&(d=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",d),a())});(function(){if(!e)if(e=s,"complete"===document.readyState)a.W=s;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",d);window.attachEvent("onload",a);var g=w;try{g=window.frameElement==t}catch(k){}document.documentElement.doScroll&&
g&&b()}})();return function(b){a.W?b():g.push(b)}}()).W=w})();return mt.f})();mt.event={};mt.event.d=function(b,a,f){b.attachEvent?b.attachEvent("on"+a,function(a){f.call(b,a)}):b.addEventListener&&b.addEventListener(a,f,w)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=w};
(function(){var b=mt.event;mt.i={};mt.i.ma=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.i.Kb=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:r;mt.i.cookieEnabled=navigator.cookieEnabled;mt.i.javaEnabled=navigator.javaEnabled();mt.i.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.i.Vb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.i.colorDepth=window.screen.colorDepth||0;mt.i.O=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.i.I=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.i.orientation=0;(function(){function a(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.i.orientation=a}a();b.d(window,"orientationchange",a)})();return mt.i})();
mt.r={};mt.r.parse=function(b){return(new Function("return ("+b+")"))()};
mt.r.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=f[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return b(e);case "boolean":return String(e);
default:if(e===t)return"null";if(e instanceof Array){var g=["["],d=e.length,n,k,f;for(k=0;k<d;k++)switch(f=e[k],typeof f){case "undefined":case "function":case "unknown":break;default:n&&g.push(","),g.push(mt.r.stringify(f)),n=1}g.push("]");return g.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+a(e.getMonth()+1)+"-"+a(e.getDate())+"T"+a(e.getHours())+":"+a(e.getMinutes())+":"+a(e.getSeconds())+'"';n=["{"];k=mt.r.stringify;for(d in e)if(Object.prototype.hasOwnProperty.call(e,d))switch(f=
e[d],typeof f){case "undefined":case "unknown":case "function":break;default:g&&n.push(","),g=1,n.push(k(d)+":"+k(f))}n.push("}");return n.join("")}}}();mt.localStorage={};mt.localStorage.aa=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(b){return w}return s};
mt.localStorage.set=function(b,a,f){var e=new Date;e.setTime(e.getTime()+f||31536E6);try{window.localStorage?(a=e.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.aa()&&(mt.localStorage.l.expires=e.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(b,a),mt.localStorage.l.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),f=b.substring(0,a)-0;if(f&&f>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.aa())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(b)}catch(e){}return t};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.aa())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(b),mt.localStorage.l.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){if(window.sessionStorage)try{window.sessionStorage.setItem(b,a)}catch(f){}};
mt.sessionStorage.get=function(b){return window.sessionStorage?window.sessionStorage.getItem(b):t};mt.sessionStorage.remove=function(b){window.sessionStorage&&window.sessionStorage.removeItem(b)};mt.Pa={};mt.Pa.log=function(b,a){var f=new Image,e="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[e]=f;f.onload=function(){f.onload=t;f=window[e]=t;a&&a(b)};f.src=b};mt.sa={};
mt.sa.Cb=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return b};
mt.sa.kc=function(b,a,f,e,g){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+f+'" height="'+e+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(g||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+f+'" height="'+e+'" src="'+a+'" flashvars="'+(g||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.m=function(b,a){var f=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return f?f[3]:t};mt.url.lc=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:t};mt.url.vb=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):t};mt.url.N=function(b){return(b=mt.url.vb(b))?b.replace(/:\d+$/,""):b};mt.url.ka=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function b(){for(var a=w,b=document.getElementsByTagName("script"),e=b.length,e=100<e?100:e,g=0;g<e;g++){var d=b[g].src;if(d&&0===d.indexOf("https://hm.baidu.com/h")){a=s;break}}return a}return h.ob=b})();var A=h.ob;
h.o={mc:"http://tongji.baidu.com/hm-web/welcome/ico",ra:"hm.baidu.com/hm.gif",Ya:/^(tongji|hmcdn).baidu.com$/,Ra:"tongji.baidu.com",Hb:"hmmd",Ib:"hmpl",gc:"utm_medium",Gb:"hmkw",ic:"utm_term",Eb:"hmci",fc:"utm_content",Jb:"hmsr",hc:"utm_source",Fb:"hmcu",ec:"utm_campaign",K:0,G:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",X:A()||"https:"===document.location.protocol?"https:":"http:",nc:0,gb:6E5,Nb:6E5,Wb:5E3,hb:5,L:1024,fb:1,z:2147483647,Qa:"hca bs kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt hh".split(" "),
P:s,ya:["a","input","button"],$a:{id:"data-hm-id",da:"data-hm-class",va:"data-hm-xpath",content:"data-hm-content",ta:"data-hm-tag",link:"data-hm-link"},xa:"data-hm-enabled",wa:"data-hm-disabled",Rb:"https://hmcdn.baidu.com/static/tongji/plugins/",Ka:["UrlChangeTracker"]};(function(){var b={C:{},d:function(a,b){this.C[a]=this.C[a]||[];this.C[a].push(b)},H:function(a,b){this.C[a]=this.C[a]||[];for(var e=this.C[a].length,g=0;g<e;g++)this.C[a][g](b)}};return h.w=b})();
(function(){function b(b,e){var g=document.createElement("script");g.charset="utf-8";a.e(e,"Function")&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=t,e()}:g.onload=function(){e()});g.src=b;var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(g,d)}var a=mt.lang;return h.load=b})();
(function(){function b(){var b="";if(h.b.c.nv){b=encodeURIComponent(document.referrer);try{window.sessionStorage?f.set("Hm_from_"+c.id,b):a.set("Hm_from_"+c.id,b,864E5)}catch(g){}}else try{b=(window.sessionStorage?f.get("Hm_from_"+c.id):a.get("Hm_from_"+c.id))||""}catch(d){}return b}var a=mt.localStorage,f=mt.sessionStorage;return h.Ba=b})();
(function(){var b=mt.lang,a=mt.f,f={S:function(b,g){return function(d){var n=d.target||d.srcElement;if(n){var k=n.getAttribute(b.$);d=d.clientX+":"+d.clientY;if(k&&k===d)n.removeAttribute(b.$);else if(g&&0<g.length&&(n=a.zb(n))&&n.length)if(k=n.length,d=n[n.length-1],1E4>k*d.split(">").length)for(d=0;d<k;d++)f.Oa(b,n[d]);else f.Oa(b,d)}}},Oa:function(a,g){for(var d={},n=String(g).split(">").length,k=0;k<n;k++)d[g]="",g=g.substring(0,g.lastIndexOf(">"));a&&(b.e(a,"Object")&&a.za)&&a.za(d)},Tb:function(a,
b){return function(d){(d.target||d.srcElement).setAttribute(a.$,d.clientX+":"+d.clientY);a&&a.s&&(b?a.s(b):a.s("#"+encodeURIComponent(this.id),d.type))}}};return h.fa=f})();
(function(){var b=mt.f,a=mt.r,f=mt.event,e=mt.lang,g=h.fa,d={$:"HM_ce",Ta:function(){if(c.cetrk&&c.cetrk.length){f.d(document,"click",g.S(d,c.cetrk));for(var e=0,k=c.cetrk.length;e<k;e++){var p;try{p=a.parse(decodeURIComponent(String(c.cetrk[e])))}catch(q){p={}}var m=p.p||"";-1===m.indexOf(">")&&(0===m.indexOf("#")&&(m=m.substring(1)),(m=b.ga(m))&&f.d(m,"click",g.Tb(d,p)))}}},za:function(b){if(c.cetrk&&c.cetrk.length)for(var e=0,g=c.cetrk.length;e<g;e++){var q;try{q=a.parse(decodeURIComponent(String(c.cetrk[e])))}catch(m){q=
{}}b.hasOwnProperty(q.p)&&d.s(q)}},s:function(a){h.b.c.et=7;var g=a&&a.k||"",g=e.g(g),d=[];if(a&&a.a&&e.e(a.a,"Object"))for(var q in a.a)if(a.a.hasOwnProperty(q)){d.push(e.g(q));var m=b.tb(a.a[q]||""),m=m?b.Ca(m):"";d.push(e.g(m))}a="";d.length&&(a="*"+d.join("*"));h.b.c.ep="ce!_iden*"+g+a;h.b.j()}};h.w.d("pv-b",d.Ta);return d})();
(function(){var b=mt.f,a=mt.lang,f=mt.event,e=mt.i,g=h.o,d=h.w,n=[],k={Sa:function(){c.ctrk&&(f.d(document,"mouseup",k.eb()),f.d(window,"unload",function(){k.Y()}),setInterval(function(){k.Y()},g.gb))},eb:function(){return function(a){a=k.qb(a);if(""!==a){var b=(g.X+"//"+g.ra+"?"+h.b.Na().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(g.z+"").length>g.L||(b+encodeURIComponent(n.join("!")+(n.length?"!":"")).length+(g.z+"").length>g.L&&k.Y(),n.push(a),(n.length>=g.hb||/\*a\*/.test(a))&&
k.Y())}}},qb:function(d){var m=d.target||d.srcElement;if(0===g.fb){var l=(m.tagName||"").toLowerCase();if("embed"==l||"object"==l)return""}var v;e.ma?(v=Math.max(document.documentElement.scrollTop,document.body.scrollTop),l=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),l=d.clientX+l,v=d.clientY+v):(l=d.pageX,v=d.pageY);d=k.wb(d,m,l,v);var f=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:l-=f/2;break;case 2:l-=f}f=
[];f.push(l);f.push(v);f.push(d.Ob);f.push(d.Pb);f.push(d.Sb);f.push(a.g(d.Qb));f.push(d.jc);f.push(d.Db);(m="a"===(m.tagName||"").toLowerCase()?m:b.pb(m))?(f.push("a"),f.push(a.g(encodeURIComponent(m.href)))):f.push("b");return f.join("*")},wb:function(g,m,l,d){g=b.Ea(m);var f=0,k=0,u=0,x=0;if(m&&(f=m.offsetWidth||m.clientWidth,k=m.offsetHeight||m.clientHeight,x=b.xb(m),u=x.left,x=x.top,a.e(m.getBBox,"Function")&&(k=m.getBBox(),f=k.width,k=k.height),"html"===(m.tagName||"").toLowerCase()))f=Math.max(f,
m.clientWidth),k=Math.max(k,m.clientHeight);return{Ob:Math.round(100*((l-u)/f)),Pb:Math.round(100*((d-x)/k)),Sb:e.orientation,Qb:g,jc:f,Db:k}},Y:function(){0!==n.length&&(h.b.c.et=2,h.b.c.ep=n.join("!"),h.b.j(),n=[])}},p={Wa:function(){c.ctrk&&setInterval(p.Xb,g.Wb)},Xb:function(){var a=e.O()+e.I();0<a-h.b.c.vl&&(h.b.c.vl=a)}};d.d("pv-b",k.Sa);d.d("pv-b",p.Wa);return k})();
(function(){var b=mt.lang,a=mt.f,f=mt.event,e=mt.i,g=h.o,d=h.w,n=+new Date,k=[],p={S:function(){return function(e){if(h.b&&h.b.P&&c.aet&&c.aet.length){var d=e.target||e.srcElement;if(d){var l=h.b.ya,f=a.getAttribute(d,g.xa)!=t?s:w;if(a.getAttribute(d,g.wa)==t)if(f)p.ba(p.ia(d,e));else{var k=a.U(d);if(b.J(l,"*")||b.J(l,k))p.ba(p.ia(d,e));else for(;d.parentNode!=t;){var f=d.parentNode,k=a.U(f),n="a"===k&&b.J(l,"a")?s:w,k="button"===k&&b.J(l,"button")?s:w,u=a.getAttribute(f,g.xa)!=t?s:w;if(a.getAttribute(f,
g.wa)==t&&(n||k||u)){p.ba(p.ia(f,e));break}d=d.parentNode}}}}}},ia:function(d,f){var l={},k=g.$a;l.id=a.getAttribute(d,k.id)||a.getAttribute(d,"id")||"";l.da=a.getAttribute(d,k.da)||a.getAttribute(d,"class")||"";l.va=a.getAttribute(d,k.va)||a.Ea(d);l.content=a.getAttribute(d,k.content)||a.Ca(d);l.ta=a.getAttribute(d,k.ta)||a.U(d);l.link=a.getAttribute(d,k.link)||a.getAttribute(d,"href")||"";l.type=f.type||"click";k=b.Ha(d.offsetTop)?d.offsetTop:0;"click"===f.type?k=e.ma?f.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):f.pageY:"touchend"===f.type&&(f.pa&&b.e(f.pa.changedTouches,"Array")&&f.pa.changedTouches.length)&&(k=f.pa.changedTouches[0].pageY);l.dc=k;return l},ba:function(a){var e=b.g;a=[+new Date-(h.b.D!==r?h.b.D:n),e(a.id),e(a.da),e(a.ta),e(a.va),e(a.link),e(a.content),a.type,a.dc].join("*");p.ca(a);b.e(this.R(),"Function")&&this.R()()},ca:function(a){a.length>g.L||(encodeURIComponent(k.join("!")+a).length>g.L&&(p.s(k.join("!")),k=[]),k.push(a))},s:function(a){h.b.c.et=5;h.b.c.ep=
a;h.b.j()},R:function(){return function(){k&&k.length&&(p.s(k.join("!")),k=[])}}};b.na()&&""!==c.aet&&d.d("pv-b",function(){f.d(document,"click",p.S());"ontouchend"in document&&f.d(window,"touchend",p.S());f.d(window,"unload",p.R())});return p})();
(function(){var b=mt.event,a=mt.i,f=h.o,e=h.w,g=+new Date,d=[],n=t,k={lb:function(){return function(){h.b&&(h.b.P&&c.aet&&c.aet.length)&&(window.clearTimeout(n),n=window.setTimeout(function(){k.Va(a.O()+a.I())},150))}},Va:function(a){k.ca([+new Date-(h.b.D!==r?h.b.D:g),a].join("*"))},ca:function(a){if(encodeURIComponent(d.join("!")+a).length>f.L||3<d.length)k.s(d.join("!")),d=[];d.push(a)},s:function(b){h.b.c.et=6;h.b.c.vh=a.I();h.b.c.ep=b;h.b.j()},R:function(){return function(){d&&d.length&&(k.s(d.join("!")),
d=[])}}};mt.lang.na()&&""!==c.aet&&e.d("pv-b",function(){b.d(window,"scroll",k.lb());b.d(window,"unload",k.R())});return k})();
(function(){var b=mt.f,a=h.o,f=h.load,e=h.Ba;h.w.d("pv-b",function(){var g=a.protocol+"//crs.baidu.com/";c.rec&&b.La(function(){for(var d=0,n=c.rp.length;d<n;d++){var k=c.rp[d][0],p=c.rp[d][1],q=b.ga("hm_t_"+k);if(p&&!(2==p&&!q||q&&""!==q.innerHTML))q="",q=Math.round(Math.random()*a.z),q=4==p?g+"hl.js?"+["siteId="+c.id,"planId="+k,"rnd="+q].join("&"):g+"t.js?"+["siteId="+c.id,"planId="+k,"from="+e(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
q].join("&"),f(q)}})})})();(function(){var b=h.o,a=h.load,f=h.Ba;h.w.d("pv-b",function(){if(c.trust&&c.vcard){var e="https://tag.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+f(),"rnd="+Math.round(Math.random()*b.z),"hm=1"].join("&");a(e)}})})();
(function(){function b(){function a(b){function e(){}for(var d=s,f=0,l=0,v=t,y=t,z=b.length,u=0,x=t,f=0;f<z;f++)if(v=b[f],v.chromeVer===n){d=s;y=v.tests;u=y.length;for(l=0;l<u;l++)if(e=g[y[l].name],e()!==y[l].expect){d=w;break}if(u&&d){x={name:"360browser",type:v.type,version:v.ver};break}}return x}var b=[];b.push({ver:"8.3",type:"fast",tests:[{name:"seamlessiframe",expect:1}],chromeVer:"42"});var g={pointerevents:function(){return"maxTouchPoints"in window.navigator?1:"msMaxTouchPoints"in window.navigator||
"mozMaxTouchPoints"in window.navigator||"webkitMaxTouchPoints"in window.navigator?9:0},webgl3D:function(){for(var a="webgl ms-webgl experimental-webgl moz-webgl opera-3d webkit-3d ms-3d 3d".split(" "),b=a.length,e="",d=document.createElement("canvas"),l=w,f=0;f<b;f++)try{if(d.getContext(a[f])){l=s;e=a[f];break}}catch(g){}return l?"webgl"===e?1:9:0},seamlessiframe:function(){return"seamless"in document.createElement("iframe")?1:0},speechsynthesis:function(){return"speechSynthesis"in window?1:"webkitSpeechSynthesis"in
window||"mozSpeechSynthesis"in window||"oSpeechSynthesis"in window||"msSpeechSynthesis"in window?9:0}},d=t,n=function(){var a=navigator.userAgent.toLowerCase().match(/chrome\/(\d+)/i);return a?a[1]:"-1"}();"-1"!==n&&(d=a(b));return d}var a=function(){var a=navigator.userAgent.toLowerCase();if(0<=a.indexOf("chrome")){var a=(a=a.match(/chrome\/(\d+)/))?a[1]:-1,e=window.document,g="track"in e.createElement("track"),e="scoped"in e.createElement("style"),d="v8Locale"in window,n=document.createElement("canvas"),
k="seamless"in document.createElement("iframe"),p=w;try{n.getContext("webgl")&&(p=s)}catch(q){}if(n=b())return"fast"===n.type?7:1;if(!p&&"31"===a)return 1;if(!(k=(k||!p)&&"38"===a))if(k=g)if(k=!e)if(k=!d){var m;a:{k=window.navigator.mimeTypes;for(m in k)if("application/vnd.chromium.remoting-viewer"===k[m].type){m=s;break a}m=w}k=!m&&46>+a}if(k)return 7;if(g&&e&&d)return 1}return-1}();return h.ab=a})();
(function(){function b(){return function(){h.b.c.nv=0;h.b.c.st=4;h.b.c.et=3;h.b.c.ep=h.ea.yb()+","+h.ea.ub();h.b.j()}}function a(){clearTimeout(x);var b;z&&(b="visible"==document[z]);u&&(b=!document[u]);k="undefined"==typeof b?s:b;if((!n||!p)&&k&&q)y=s,l=+new Date;else if(n&&p&&(!k||!q))y=w,v+=+new Date-l;n=k;p=q;x=setTimeout(a,100)}function f(a){var l=document,b="";if(a in l)b=a;else for(var e=["webkit","ms","moz","o"],d=0;d<e.length;d++){var u=e[d]+a.charAt(0).toUpperCase()+a.slice(1);if(u in l){b=
u;break}}return b}function e(l){if(!("focus"==l.type||"blur"==l.type)||!(l.target&&l.target!=window))q="focus"==l.type||"focusin"==l.type?s:w,a()}var g=mt.event,d=h.w,n=s,k=s,p=s,q=s,m=+new Date,l=m,v=0,y=s,z=f("visibilityState"),u=f("hidden"),x;a();(function(){var l=z.replace(/[vV]isibilityState/,"visibilitychange");g.d(document,l,a);g.d(window,"pageshow",a);g.d(window,"pagehide",a);"object"==typeof document.onfocusin?(g.d(document,"focusin",e),g.d(document,"focusout",e)):(g.d(window,"focus",e),
g.d(window,"blur",e))})();h.ea={yb:function(){return+new Date-m},ub:function(){return y?+new Date-l+v:v}};d.d("pv-b",function(){g.d(window,"unload",b())});d.d("duration-send",b());d.d("duration-done",function(){l=m=+new Date;v=0});return h.ea})();
(function(){var b=mt.lang,a=h.o,f=h.load,e={Lb:function(e){if((window._dxt===r||b.e(window._dxt,"Array"))&&"undefined"!==typeof h.b){var d=h.b.T();f([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(d)].join(""),e)}},bc:function(a){if(b.e(a,"String")||b.e(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.ib=e})();
(function(){function b(a,b,e,d){if(!(a===r||b===r||d===r)){if(""===a)return[b,e,d].join("*");a=String(a).split("!");for(var u,f=w,g=0;g<a.length;g++)if(u=a[g].split("*"),String(b)===u[0]){u[1]=e;u[2]=d;a[g]=u.join("*");f=s;break}f||a.push([b,e,d].join("*"));return a.join("!")}}function a(l){for(var b in l)if({}.hasOwnProperty.call(l,b)){var d=l[b];e.e(d,"Object")||e.e(d,"Array")?a(d):l[b]=String(d)}}var f=mt.url,e=mt.lang,g=mt.r,d=mt.i,n=h.o,k=h.w,p=h.ib,q=h.load,m={Q:[],Z:0,Ia:w,B:{ua:"",page:""},
init:function(){m.h=0;k.d("pv-b",function(){m.jb();m.mb()});k.d("pv-d",function(){m.nb();m.B.page=""});k.d("stag-b",function(){h.b.c.api=m.h||m.Z?m.h+"_"+m.Z:"";h.b.c.ct=[decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),m.B.ua,m.B.page].join("!")});k.d("stag-d",function(){h.b.c.api=0;m.h=0;m.Z=0})},jb:function(){var a=window._hmt||[];if(!a||e.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var l=arguments[b];e.e(l,"Array")&&(a.cmd[a.id].push(l),
"_setAccount"===l[0]&&(1<l.length&&/^[0-9a-f]{32}$/.test(l[1]))&&(l=l[1],a.id=l,a.cmd[l]=a.cmd[l]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},mb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],e=/^_track(Event|MobConv|Order|RTEvent)$/,d=0,u=b.length;d<u;d++){var f=b[d];e.test(f[0])?m.Q.push(f):m.qa(f)}a.cmd[c.id]={push:m.qa}},nb:function(){if(0<m.Q.length)for(var a=0,b=m.Q.length;a<b;a++)m.qa(m.Q[a]);m.Q=t},qa:function(a){var b=a[0];if(m.hasOwnProperty(b)&&
e.e(m[b],"Function"))m[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(m.h|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||s===a))m.h|=2,h.b.Fa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){m.h|=4;h.b.c.sn=h.b.Da();h.b.c.et=0;h.b.c.ep="";h.b.c.vl=d.O()+d.I();h.b.c.kb=0;h.b.la?(h.b.c.nv=0,h.b.c.st=4):h.b.la=s;var b=h.b.c.u,e=h.b.c.su;h.b.c.u=n.protocol+"//"+document.location.host+a[1];m.Ia||(h.b.c.su=document.location.href);
h.b.j();h.b.c.u=b;h.b.c.su=e;h.b.D=+new Date}},_trackEvent:function(a){2<a.length&&(m.h|=8,h.b.c.nv=0,h.b.c.st=4,h.b.c.et=4,h.b.c.ep=e.g(a[1])+"*"+e.g(a[2])+(a[3]?"*"+e.g(a[3]):"")+(a[4]?"*"+e.g(a[4]):""),h.b.j())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){m.Z++;for(var f=(h.b.c.cv||"*").split("!"),u=f.length;u<b-1;u++)f.push("*");f[b-1]=d+"*"+e.g(a[2])+"*"+e.g(a[3]);h.b.c.cv=f.join("!");a=h.b.c.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.Ub("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var d=e.g(a[1]);a=e.g(a[2]);if(d!==r&&a!==r){var f=decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),f=b(f,d,1,a);h.b.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var d=e.g(a[1]);a=e.g(a[2]);if(d!==r&&a!==r){var f=m.B.ua,f=b(f,d,2,a);m.B.ua=f}}},_setPageTag:function(a){if(!(3>a.length)){var d=e.g(a[1]);a=e.g(a[2]);
if(d!==r&&a!==r){var f=m.B.page,f=b(f,d,3,a);m.B.page=f}}},_setReferrerOverride:function(a){1<a.length&&(h.b.c.su=a[1].charAt&&"/"===a[1].charAt(0)?n.protocol+"//"+window.location.host+a[1]:a[1],m.Ia=s)},_trackOrder:function(b){b=b[1];e.e(b,"Object")&&(a(b),m.h|=16,h.b.c.nv=0,h.b.c.st=4,h.b.c.et=94,h.b.c.ep=g.stringify(b),h.b.j())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])m.h|=32,h.b.c.et=93,h.b.c.ep=a,h.b.j()},_trackRTPageview:function(b){b=b[1];e.e(b,"Object")&&
(a(b),b=g.stringify(b),512>=encodeURIComponent(b).length&&(m.h|=64,h.b.c.rt=b))},_trackRTEvent:function(b){b=b[1];if(e.e(b,"Object")){a(b);b=encodeURIComponent(g.stringify(b));var d=function(a){var b=h.b.c.rt;m.h|=128;h.b.c.et=90;h.b.c.rt=a;h.b.j();h.b.c.rt=b},f=b.length;if(900>=f)d.call(this,b);else for(var f=Math.ceil(f/900),k="block|"+Math.round(Math.random()*n.z).toString(16)+"|"+f+"|",u=[],x=0;x<f;x++)u.push(x),u.push(b.substring(900*x,900*x+900)),d.call(this,k+u.join("|")),u=[]}},_setUserId:function(a){a=
a[1];p.Lb();p.bc(a)},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],w===a||s===a))h.b.Ga=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],w===a||s===a))h.b.P=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.b.c.et=3,h.b.c.ep=a,h.b.j())):k.H("duration-send");k.H("duration-done")},_require:function(a){1<a.length&&(a=a[1],n.Ya.test(f.N(a))&&q(a))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1];a=a[2];if(e.J(n.Ka,d)&&e.e(a,"Function")&&
(b.plugins=b.plugins||{},b.F=b.F||{},b.plugins[d]=a,b.A=b.A||[],a=b.A.slice(),d&&a.length&&a[0][1]===d))for(var f=0,u=a.length;f<u;f++){var g=a[f][2]||{};if(b.plugins[d]&&!b.F[d])b.F[d]=new b.plugins[d](g),b.A.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1],f=a[2]||{};if(e.J(n.Ka,d))if(b.plugins=b.plugins||{},b.F=b.F||{},b.plugins[d]&&!b.F[d])b.F[d]=new b.plugins[d](f);else{b.A=b.A||[];for(var f=0,u=b.A.length;f<u;f++)if(b.A[f][1]===d)return;b.A.push(a);m._require([t,
n.Rb+d+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=e.g(a[1]),d="";a=a[2];if(e.e(a,"Object")){var d=[],f;for(f in a)a.hasOwnProperty(f)&&(d.push(e.g(f)),d.push(e.g(a[f])));d="*"+d.join("*")}h.b.c.et=7;h.b.c.ep="ce!_iden*"+b+d;h.b.j()}}};m.init();h.Za=m;return h.Za})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=s,this.c={},this.Ga=this.Fa=s,this.P=l.P,this.ya=g.na()&&0<c.aet.length?c.aet.split(","):"",this.la=w,this.init())}var a=mt.url,f=mt.Pa,e=mt.sa,g=mt.lang,d=mt.cookie,n=mt.i,k=mt.localStorage,p=mt.sessionStorage,q=mt.r,m=mt.event,l=h.o,v=h.ab,y=h.load,z=h.w;b.prototype={oa:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},
Ja:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},V:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.Ja(b,c.dm[d]))return s}else{var e=a.N(b);if(e&&this.oa(e,c.dm[d]))return s}return w},T:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.oa(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ha:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.Ja(document.location.href,
d))return d.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"},Ab:function(){if(!document.referrer)return l.G-l.K>c.vdur?1:4;var b=w;this.V(document.referrer)&&this.V(document.location.href)?b=s:(b=a.N(document.referrer),b=this.oa(b||"",document.location.hostname));return b?l.G-l.K>c.vdur?1:4:3},getData:function(a){try{return d.get(a)||p.get(a)||k.get(a)}catch(b){}},setData:function(a,b,e){try{d.set(a,b,{domain:this.T(),path:this.ha(),M:e}),e?k.set(a,b,e):p.set(a,b)}catch(f){}},Ub:function(a){try{d.set(a,
"",{domain:this.T(),path:this.ha(),M:-1}),p.remove(a),k.remove(a)}catch(b){}},$b:function(){var a,b,e,f,g;l.K=this.getData("Hm_lpvt_"+c.id)||0;13===l.K.length&&(l.K=Math.round(l.K/1E3));b=this.Ab();a=4!==b?1:0;if(e=this.getData("Hm_lvt_"+c.id)){f=e.split(",");for(g=f.length-1;0<=g;g--)13===f[g].length&&(f[g]=""+Math.round(f[g]/1E3));for(;2592E3<l.G-f[0];)f.shift();g=4>f.length?2:3;for(1===a&&f.push(l.G);4<f.length;)f.shift();e=f.join(",");f=f[f.length-1]}else e=l.G,f="",g=1;this.setData("Hm_lvt_"+
c.id,e,c.age);this.setData("Hm_lpvt_"+c.id,l.G);e=d.Mb(this.T(),this.ha());if(0===c.nv&&this.V(document.location.href)&&(""===document.referrer||this.V(document.referrer)))a=0,b=4;this.c.nv=a;this.c.st=b;this.c.cc=e;this.c.lt=f;this.c.lv=g},Na:function(){for(var a=[],b=this.c.et,d=+new Date,e=0,f=l.Qa.length;e<f;e++){var g=l.Qa[e],k=this.c[g];"undefined"!==typeof k&&""!==k&&("tt"!==g||"tt"===g&&0===b)&&(("ct"!==g||"ct"===g&&0===b)&&("kb"!==g||"kb"===g&&3===b))&&a.push(g+"="+encodeURIComponent(k))}switch(b){case 0:this.c.rt&&
a.push("rt="+encodeURIComponent(this.c.rt));break;case 5:a.push("_lpt="+this.D);a.push("_ct="+d);break;case 6:a.push("_lpt="+this.D);a.push("_ct="+d);break;case 90:this.c.rt&&a.push("rt="+this.c.rt)}return a.join("&")},ac:function(){this.$b();this.c.si=c.id;this.c.sn=this.Da();this.c.su=document.referrer;this.c.hh=window.location.hash;this.c.ds=n.Vb;this.c.cl=n.colorDepth+"-bit";this.c.ln=String(n.language).toLowerCase();this.c.ja=n.javaEnabled?1:0;this.c.ck=n.cookieEnabled?1:0;this.c.bs=v;this.c.lo=
"number"===typeof _bdhm_top?1:0;this.c.fl=e.Cb();this.c.v="1.2.50";this.c.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.c.tt=document.title||"";this.c.vl=n.O()+n.I();var b=document.location.href;this.c.cm=a.m(b,l.Hb)||"";this.c.cp=a.m(b,l.Ib)||a.m(b,l.gc)||"";this.c.cw=a.m(b,l.Gb)||a.m(b,l.ic)||"";this.c.ci=a.m(b,l.Eb)||a.m(b,l.fc)||"";this.c.cf=a.m(b,l.Jb)||a.m(b,l.hc)||"";this.c.cu=a.m(b,l.Fb)||a.m(b,l.ec)||""},init:function(){try{this.ac(),0===this.c.nv?this.Zb():this.Aa(),h.b=this,
this.cb(),this.bb(),z.H("pv-b"),this.Yb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(l.X+"//"+l.ra+"?"+b.join("&"))}},Yb:function(){function a(){z.H("pv-d")}this.Fa?(this.la=s,this.c.et=0,this.c.ep="",this.c.vl=n.O()+n.I(),this.j(a)):a();this.D=+new Date},j:function(a){if(this.Ga){var b=this;b.c.rnd=Math.round(Math.random()*l.z);z.H("stag-b");var d=l.X+"//"+l.ra+"?"+
b.Na();z.H("stag-d");b.Xa(d);f.log(d,function(d){b.Ma(d);g.e(a,"Function")&&a.call(b)})}},cb:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.N(document.referrer)===l.Ra?1:0,f=a.m(b,"jn"),g=/^heatlink$|^select$|^pageclick$|^customevent$/.test(f);b&&(d.test(b)&&e&&g)&&(this.c.rnd=Math.round(Math.random()*l.z),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset","utf-8"),b.setAttribute("src",l.protocol+"//"+c.js+f+".js?"+this.c.rnd),
f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(b,f))},bb:function(){if(window.postMessage&&window.self!==window.parent){var b=this;m.d(window,"message",function(d){if(a.N(d.origin)===l.Ra){var e=d.data||{};d=e.sd||"";var e=e.jn||"",f=/^customevent$/.test(e);RegExp(c.id).test(d)&&f&&(b.c.rnd=Math.round(Math.random()*l.z),y(l.protocol+"//"+c.js+e+".js?"+b.c.rnd))}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},Xa:function(a){var b;
try{b=q.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.c.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);p.set("Hm_unsent_"+c.id,q.stringify(b))},Ma:function(a){var b;try{b=q.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?p.set("Hm_unsent_"+c.id,q.stringify(b)):this.Aa()}},Aa:function(){p.remove("Hm_unsent_"+
c.id)},Zb:function(){var a=this,b;try{b=q.parse(p.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var e=function(b){f.log(l.X+"//"+b,function(b){a.Ma(b)})},g=0;g<b.length;g++)e(b[g])},Da:function(){return Math.round(+new Date/1E3)%65535}};return new b})();
(function(){var b=mt.event,a=mt.lang,f=h.o;if(c.kbtrk&&"undefined"!==typeof h.b){h.b.c.kb=a.Ha(h.b.c.kb)?h.b.c.kb:0;var e=function(){h.b.c.et=85;h.b.c.ep=h.b.c.kb;h.b.j()};b.d(document,"keyup",function(){h.b.c.kb++});b.d(window,"unload",function(){e()});setInterval(e,f.Nb)}})();var B=h.o,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.i,a=mt.lang,f=mt.event,e=mt.r;if("undefined"!==typeof h.b&&(c.med||(!b.ma||7<b.Kb)&&c.cvcc)){var g,d,n,k,p=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},q=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===w)return w},m=function(b,d){var f={};f.n=g;f.t="clk";f.v=b;if(d){var k=d.getAttribute("href"),l=d.getAttribute("onclick")?""+d.getAttribute("onclick"):t,m=d.getAttribute("id")||"";n.test(k)?(f.sn="mediate",
f.snv=k):a.e(l,"String")&&n.test(l)&&(f.sn="wrap",f.snv=l);f.id=m}h.b.c.et=86;h.b.c.ep=e.stringify(f);h.b.j();for(f=+new Date;400>=+new Date-f;);};if(c.med)d="/zoosnet",g="swt",n=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,k={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(n.test(e)||n.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){d="/other-comm";g="other";n=c.cvcc.q||r;var l=c.cvcc.id||r;k={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f,g=0,k=b.length;g<k;g++)d=b[g],n!==r?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),l?(d=d.getAttribute("id"),(n.test(e)||n.test(f)||l.test(d))&&
a.push(b[g])):(n.test(e)||n.test(f))&&a.push(b[g])):l!==r&&(d=d.getAttribute("id"),l.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof k&&"undefined"!==typeof n){var v;d+=/\/$/.test(d)?"":"/";var y=function(b,e){if(v===e)return m(d+b,e),w;if(a.e(e,"Array")||a.e(e,"NodeList"))for(var f=0,g=e.length;f<g;f++)if(v===e[f])return m(d+b+"/"+(f+1),e[f]),w};f.d(document,"mousedown",function(b){b=b||window.event;v=b.target||b.srcElement;var d={};for(q(k,function(b,e){d[b]=a.e(e,"Function")?e():document.getElementById(e)});v&&
v!==document&&q(d,y)!==w;)v=v.parentNode})}}})();(function(){var b=mt.f,a=mt.lang,f=mt.event,e=mt.r;if("undefined"!==typeof h.b&&a.e(c.cvcf,"Array")&&0<c.cvcf.length){var g={Ua:function(){for(var a=c.cvcf.length,e,k=0;k<a;k++)(e=b.ga(decodeURIComponent(c.cvcf[k])))&&f.d(e,"click",g.fa())},fa:function(){return function(){h.b.c.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.c.ep=e.stringify(a);h.b.j()}}};b.La(function(){g.Ua()})}})();
(function(){var b=mt.event,a=mt.r;if(c.med&&"undefined"!==typeof h.b){var f=+new Date,e={n:"anti",sb:0,kb:0,clk:0},g=function(){h.b.c.et=86;h.b.c.ep=a.stringify(e);h.b.j()};b.d(document,"click",function(){e.clk++});b.d(document,"keyup",function(){e.kb=1});b.d(window,"scroll",function(){e.sb++});b.d(window,"unload",function(){e.t=+new Date-f;g()});b.d(window,"load",function(){setTimeout(g,5E3)})}})();c.spa!==r&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]));})();
